### PR TITLE
Add an API call to gather information about the instance

### PR DESCRIPTION
**Pull request by mroman-redhat**

### CODE REVIEW

**Comment by mroman-redhat** [comment]
This update will require adding a new cluster role to the JupyterHub Service Account.

**Comment by vpavlin** [comment]
Can you please fix the conflicts?

I tested this and got `cluster_id` back, but not `segment_key` - any idea why?

**Comment by DaoDaoNoCode** [comment]
@vpavlin Segment key needs to be added manually as a Secret resource by the admin user. Because different users may use different `segment_key`.

**Comment by vpavlin** [comment]
lgtm

**Pull request merged**
